### ISSUE TITLE
Please tag a release when ready

### ISSUE THREAD

**Issue by Justinzobel** [osendott/arch-frost#1]
So it can be downloaded as a tar.xz/gz/bz and packaged for other distros :D

**Comment by osendott** [comment]
in the mean time, you can grab tar.gz from the repo ;)

**Comment by Justinzobel** [comment]
ahh didn't see it, thanks.

**Comment by osendott** [comment]
i'm gonna try to finish up the light theme tonight and hit the dark hard tomorrow. perhaps tomorrow night it'll be finished. I need more free time.
